source=/nix/store/is9hhzz5gnazqkw52kaq9azs81an1brp-catppuccin-hyprlock-0-unstable-2025-06-02/frappe.conf
source=/nix/store/hjs91qw06x9sf8al0qj92cych9hiqcza-hyprland-mauve-accent.conf
source=/nix/store/is9hhzz5gnazqkw52kaq9azs81an1brp-catppuccin-hyprlock-0-unstable-2025-06-02/hyprlock.conf
background {
  blur_passes=3
  blur_size=8
  path=screenshot
}

general {
  disable_loading_bar=true
  grace=0
}

input-field {
  size=250, 60
  dots_size=0.200000
  dots_spacing=0.200000
  fade_on_empty=false
  outline_thickness=2
}
